@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Person_Ext(personAlias, "Cliente", "Quiere hacer uso del sistema de mensajes")

Container_Boundary(servidor, "Servidor") {
    Component(directorio, "Directorio", "Es el directorio encargado de publicar el API a los clientes y redirigir las peticiones a los servicios correspondientes")
    Component(nodo1, "Node manager mensajes", "Se encarga de la gestión de los nodos de los balanceadores de carga y guarda información sobre ellos")
    Component(nodo2, "Node manager usuarios", "Se encarga de la gestión de los nodos de los balanceadores de carga y guarda información sobre ellos")
   
       
}

Container_Boundary(bd1, "Base de datos de usuarios") {
 ContainerDb(user_db, "Base de datos", "Se encarga de mantener la persistencia de los datos sobre usuarios"){
       Component(api2, "Server_db", "Expone las operaciones permitidas en la BD para el usuario o servicios que quieran acceder a ella")
       Component(persistencia2, "DB", "Se encarga de manipular los datos")

}
}

Container_Boundary(bd2, "Base de datos de mensajes") {
 ContainerDb(message_db, "Base de datos", "Se encarga de mantener la persistencia de los datos sobre mensajes"){
       Component(api1, "Server_db", "Expone las operaciones permitidas en la BD para el usuario o servicios que quieran acceder a ella")
       Component(persistencia1, "DB", "Se encarga de manipular los datos")
}
}

Container_Boundary(servidor1, "Servidor de mensajes") {
    Component(mensajes, "Servicio de mensajes", "Recibe peticiones relacionadas con la gestión de mensajes de la app, las procesa y devuelve una respuesta")

}

Container_Boundary(servidor2, "Servidor de usuarios") {
    Component(usuarios, "Servicio de usuarios", "Recibe peticiones relacionadas con la gestión de usuarios de la app, las procesa y devuelve una respuesta")

}


Container_Boundary(balanceador1, "Balanceador de carga") {
 Component(bal1, "Balanceador de carga de usuarios", "Se encarga de distribuír las peticiones a los diferentes servidores")


}


Container_Boundary(balanceador2, "Balanceador de carga") {
 Component(bal2, "Balanceador de carga de mensajes", "Se encarga de distribuír las peticiones a los diferentes servidores")
} 











Rel(personAlias, directorio, "Envía", "Petición")
Rel(directorio, personAlias, "Devuelve", "Respuesta")

Rel(bal2, directorio, "Responde", "Resultado")
Rel(directorio, bal2, "Redirige", "Petición")



Rel(bal1, directorio, "Responde", "Resultado")
Rel(directorio, bal1, "Redirige", "Petición")

Rel(directorio, nodo1, "Envía", "Petición")
Rel(nodo1, directorio, "Responde", "Respuesta")

Rel(directorio, nodo2, "Envía", "Petición")
Rel(nodo2, directorio, "Responde", "Respuesta")






Rel(bal1, usuarios, "Responde", "Resultado")
Rel(usuarios, bal1, "Redirige", "Petición")

Rel(bal2, mensajes, "Responde", "Resultado")
Rel(mensajes, bal2, "Redirige", "Petición")

Rel(mensajes, api1, "Envía", "Petición")
Rel(api1, mensajes, "Responde", "Respuesta")

Rel(usuarios, api2, "Envía", "Petición")
Rel(api2, usuarios, "Responde", "Respuesta")

Rel(api1, persistencia1, "Envía", "Petición")
Rel(persistencia1, api1, "Responde", "Respuesta")

Rel(api2, persistencia2, "Envía", "Petición")
Rel(persistencia2, api2, "Responde", "Respuesta")
@enduml